language: python
python:
    - "2.7"

env:
    matrix:
        - ACTION="test-rest-service-v2_1-client"
        - ACTION="test-rest-service-v2-client"
        - ACTION="test-rest-service-v1-client"
        - ACTION="test-system-workflows"
        - ACTION="flake8"

install:
    - pip install tox
script:
    - ./run-tests.sh $ACTION
