version: 2
jobs:
  build:
    docker:
      - image: python:2.7.13

    working_directory: ~/cloudify-local-bootstrap

    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run static analysis
          command: tox -e flake8
      - run:
          name: Run test cases
          command: tox -e py27
